### ISSUE TITLE
Low accuracy of the Red-Wine-Quality-Project

### ISSUE THREAD

**Issue by MYCIN-AI-Club** [MYCIN-AI-Club/MachineLearning-Bootcamp01#11]
The notebooks attached have low accuracies of 70.31% for Random Forest and 52.5% for Multiple Linear Regression. 

This issue aims at contributions with better accuracy using new models or improved versions of these models.

**Comment by AAnirudh07** [comment]
I'd like to be assigned to this issue pls

**Comment by Radhika19Gupta** [comment]
Hello @MYCIN-AI-Club.. I would like this to be assigned to me as my first issue.

**Comment by MYCIN-AI-Club** [comment]
Dear @Radhika19Gupta , We will have to go by FCFS. So @AAnirudh07 you're being assigned the same.

**Comment by AAnirudh07** [comment]
Thank you!
