### ISSUE TITLE
Student Performance Data Set Model

### ISSUE THREAD

**Issue by narwar-veer** [MYCIN-AI-Club/MachineLearning-Bootcamp01#17]
Addition of ML model on Student Performance Data Set, Please assign me to do the same!

**Comment by MYCIN-AI-Club** [comment]
Dear @narwar-veer , your initiative is appreciated but you created this issue in a different repository, please create in the Data-Analysis-Projects and ask for assigning it to you.

**Comment by narwar-veer** [comment]
Okay
