### ISSUE TITLE
Addition of Readme in Diabetes Prediction

### ISSUE THREAD

**Issue by Garvit414** [MYCIN-AI-Club/MachineLearning-Bootcamp01#22]
I want to make and add Readme file in Diabetes Prediction Folder. Please Assign it to me @MYCIN-AI-Club

**Comment by ayu3011** [comment]
I find myself skilled for the task. Please assign it to me @MYCIN-AI-Club

**Comment by cyborg-joshi** [comment]
I find myself capable to do this task. Please assign me this task.

**Comment by MYCIN-AI-Club** [comment]
@Garvit414 you have created the issue which is great. But, this project was initially made by @ayu3011 so we'll be assigning it to her. You may look for improvement after she adds the basic readme. The same goes for @cyborg-joshi

**Comment by MYCIN-AI-Club** [comment]
Great work @ayu3011 !!
