### ISSUE TITLE
Organize Diabetes Project

### ISSUE THREAD

**Issue by MYCIN-AI-Club** [MYCIN-AI-Club/MachineLearning-Bootcamp01#9]
Make a folder for all related files containing Readme, ipynb file and the dataset (csv format).

**Comment by manasrai1406** [comment]
I find myself skilled enough to do the task please assign me the same.

**Comment by MYCIN-AI-Club** [comment]
> I find myself skilled enough to do the task please assign me the same.

Your initiative is appreciated. You have been assigned the issue. <a href="https://github.com/manasrai1406">@manasrai1406</a>. We hope that you will solve the issue and it will help you improve your skills.

**Comment by codemaniac-sahil** [comment]
Hello @manasrai1406 I want to know are you working on this issue.

**Comment by manasrai1406** [comment]
Yes I'm working on this issue

**Comment by codemaniac-sahil** [comment]
Okay @manasrai1406

**Comment by MYCIN-AI-Club** [comment]
The task has been done. Looking forward to see you on new issues.
